### ISSUE TITLE
Getting error when running k-mers gwas for snp-matirx 

### ISSUE THREAD

**Issue by vinod1981** [voichek/kmersGWAS#137]
Dear Yoav,
Actually we are facing some issue with Bonferroni and FDR threshold and want to see if permutation using a subset of SNPs is improving it or not. So ,I am using k-mers-based gwas pipeline for snp matrix but getting an error:
Here is the script:`
python kmers_gwas.py --pheno kmers_leaf_cd.txt --kmers_table kmers_table --maf 0.02 -p 10 -l 31 --dont_run_on_kmers --run_on_snps_two_steps --snp_matrix SNP_Matrix_plink --snps_number 10000 --kinship_snps --gemma_path gemma-0.98.5-linux-static-AMD64  --outdir leaf_Cd_All_SNP_Matrix >>gwas_run.log.txt 2>&1 ` 
I quickly generated snp martrix using plink commands from: #119 

An getting following error:
```
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Calls: as.matrix -> read.csv -> read.table
Execution halted
Traceback (most recent call last):
  File "kmers_gwas.py", line 278, in <module>
    main()
  File "kmers_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]
IOError: [Errno 2] No such file or directory: 'pheno.phenotypes_and_permutations'
```

Even I used a patch provided in the same issue and also tried by using or not using phenotype information in .fam file. But the error is consistent and not going. There were some missing phenotypes in .fam file, I replaced them with dummy values but the error is still not going.

Please provide a solution.

Thanks,

Vinod

**Comment by voichek** [comment]
Dear Vinod,

Is it possible that is cannot find the kinship matrix `SNP_Matrix_plink.kinship`?

Second, I suspect the code will also not work afterwards due to the use of gemme, 0.98. 

Let me know if this works or you get other error.

Yoav

**Comment by voichek** [comment]
I take my second comment back. The patch should work for SNPs. Let me know regarding the kinship

**Comment by vinod1981** [comment]
Dear Yoav,
I just tried gemma version 0.96, the one provided in external program and still I am getting the same error.
My kinship matrices from k-mers-based gwas and SNP-based GWAS are quite same so for test I was using k-mers-based kinship by just changing the file_name same as SNP_matrix.
Thanks

**Comment by voichek** [comment]
Regarding the pheno it shouldn't be a problem

To be clear the file `SNP_Matrix_plink.kinship` exist?

If you can please zip the run folder and upload it, it can be useful.

**Comment by vinod1981** [comment]
Dear Yoav,
Yes kinship file exists in the same folder.
If I understand correctly, you need only gwas _outdir or a folder with all the files. gwas_outdir folder, I am attaching here.
[leaf_Cd_All_SNP_Matrix.zip](https://github.com/voichek/kmersGWAS/files/11407715/leaf_Cd_All_SNP_Matrix.zip)

Thanks,
Vinod

**Comment by voichek** [comment]
1. Your phenotype file is not in the right format (header).
2. Are you sure the names in your phenotype file are exactly the same as in the SNP matrix file?

**Comment by vinod1981** [comment]
Dear Yoav,
I am sorry for late response. Actually, there was a problem in my plink .FAM file format. When I used plink tool to convert my VCF to plink files, kmersGWAS was not reading it properly and throwing an error but when I used other tools to convert VCF to plink files, kmersGWAS was working fine.
Still, I have few questions: 1. Individuals in my SNP matrix (plink files) are exactly in same order with kmers_table.name and then I generated a kinship matrix out of it which obviously contains same sequence of individuals. Do I also need to keep this individuals sequence (order) same in phenotype files? Because there are some NAs in my phenotype file which are not accepted in kmersGWAS so I can only keep individuals with phenotypes.
2. Do, kmersGWAS reads phenotype information already available in .FAM file, or it replaces this information from phenotype file.  
3. Doesn't kmersGWAS collect SNPs information passing the 5% or 10% significant threshold level in snps directories (results)?

And regarding your last reply and comment 1, I always use a different header for every trait and I never got any error, is it a wrong way of doing analysis? 

Thanks,

Vinod
