### ISSUE TITLE
no snps bim, bed files

### ISSUE THREAD

**Issue by Udi-Lan** [voichek/kmersGWAS#72]
Hi Yoav,

When running with the option of analyzing snp`s I get this error several times:

GEMMA 0.98.3 (2020-11-28) by Xiang Zhou and team (C) 2012-2020
error! fail to open .bim file: run_GWAS_FT10_snp/snps/snps.plink.bim
error! fail to open .bed file: run_GWAS_FT10_snp/snps/snps.plink.bed

And than:
Traceback (most recent call last):
  File "../../kmers_gwas.py", line 278, in <module>
    main()
  File "../../kmers_gwas.py", line 235, in main
    th_5per = get_threshold_from_perm(res, "P", args.n_permutations, 0.05)
  File "/home/.../kmer_gwas/src/py/functions.py", line 110, in get_threshold_from_perm
    pvals.append(best_pvals[prefix + str(i)])
KeyError: 'P1'

I run the command:
$ python2.7 ../../kmers_gwas.py --pheno FT10.pheno --kmers_table A_thaliana_1001G_kmers_table/kmers_table -l 31 -p 8 --run_on_snps_one_step --gemma_path /home/.../kmer_gwas/gemma-0.98.3-linux-static --outdir run_GWAS_FT10_snp

In the kmer and output folder I see a lot of files (bed bim txt)
And in snps folder there are bed and bim files that seems to be corrupted.

Thank you for your support
Udi

**Comment by Udi-Lan** [comment]
I see now that I didn't have --snp_matrix
