### ISSUE TITLE
error running kmers_gwas.py

### ISSUE THREAD

**Issue by Udi-Lan** [voichek/kmersGWAS#75]
Dear Yoav,
I`m trying to run the Arabidopsis example on our cluster.
The error massage I get is:

Traceback (most recent call last):
  File "../../kmers_gwas.py", line 278, in <module>
    main()
  File "../../kmers_gwas.py", line 153, in main
    fam_fn = get_file_type_in_dir(paths["kmers_associations_dir"], "%s.fam" % p_name)
  File "/.../v0_2_beta/src/py/functions.py", line 10, in get_file_type_in_dir
    raise Exception("File count not = 1 %s %d\n%s"  % (type_suffix, len(fns), dir_name))
Exception: File count not = 1 phenotype_value.fam 0
run_GWAS_FT10/kmers

I see that there is an error in the associate_kmers.log file (attached)

Thank you
Udi

[associate_kmers.log](https://github.com/voichek/kmersGWAS/files/5808297/associate_kmers.log)

**Comment by Udi-Lan** [comment]
I see now its something that need to be installed on my end.
I`ll close the issue myself as usual ... :)
