### ISSUE TITLE
Error When Running on Arabidopsis Flowering Time Example

### ISSUE THREAD

**Issue by cedatorma** [voichek/kmersGWAS#92]
Hello Voichek,

I've been trying to get kmersGWAS up and running on a super-computer cluster on the Arabidopsis Flowering Time Example. First of all, I've been getting some problems when running the script using multithreading (-p 8), giving an error when trying to access kmer patterns, suggesting that some information is being lost, perhaps from parallel processes not completing. This might be a particular problem to the computer cluster I am using, but it might not be so important at the time being.

I tried running the example script without multithreading (-p 1). This appears to bypass the previous error, but when it comes to computing significant kmers which pass different p-value percentile threshold cutoffs, the following error results: 

Traceback (most recent call last):
  File "../../kmers_gwas.py", line 278, in <module>
    main()
  File "../../kmers_gwas.py", line 247, in main
    th_5per = get_threshold_from_perm(res, "P", args.n_permutations, 0.05)
  File "/gpfs/fs0/scratch/j/jparkin/ctorma/kmersGWAS/src/py/functions.py", line 110, in get_threshold_from_perm
    pvals.append(best_pvals[prefix + str(i)])
KeyError: 'P1'

Now, there are output files for significant kmers produced: pass_threshold_5per, pass_threshold_10per. Perhaps the error indicates that these are kmers which pass the 1% top p-value threhold? Any help in elucidating the nature of this error would be greatly appreciated.

**Comment by voichek** [comment]
Dear cedatorma,

1. Regarding "an error when trying to access kmer patterns", this is not clear to me. Can you please copy-paste here what command you run and what is the error or exact problematic output you got.
2. Can you please zip the gwas results folder for the flowering time and post it here. Using this I can more easily pin-point the issue.
3. Can you check if you can run the GEMMA from `external_programs/gemma_0_96`? Just run it without any parameters and see it can run.

Best,
Yoav

**Comment by cedatorma** [comment]
Hi voichek,

1) Here is the command I'm using to run kmersGWAS. I am running it from the ./example/flowering_time_arabidopsis/ directory, and it is pretty much verbatim from the ./run_example.sh code, except for multi-threading (-p) being set to 1 to remove some computer cluster specific errors:

python2.7 ../../kmers_gwas.py --pheno FT10.pheno --kmers_table A_thaliana_1001G_kmers_table/kmers_table -l 31 -p 1 --outdir run_GWAS_FT10

2) The zip of the results directory is attached.

3.1) Gemma appears to run without a problem, just an introductory screen, no error messages. 

3.2) For future consideration: One interesting thing I noticed is that when I tried to run gemma packaged with kmersGWAS on my desktop (Ubuntu 20.04), I received an error that libgfortran.so.3 does not exist. This appears to be a particular error associated with Ubuntu 20.04, which does not support g++-6. This could be fixed with a work-around to installing gcc++-6 : https://stackoverflow.com/questions/62908955/how-to-install-libgfortran-so-3-on-ubuntu-20-04 .

[run_GWAS_FT10.zip](https://github.com/voichek/kmersGWAS/files/6571717/run_GWAS_FT10.zip)

**Comment by voichek** [comment]
Dear cedatorma,

I am a bit confused. The output of the pipeline looks good, and actually you have files in the directory (e.g. `threshold_5per`) that are created in the script after it supposedly crashed. Can you please download the release again and remove all the scripts and the output of the pipeline and then run again?

Let me know if this happens again.

Best,
Yoav

**Comment by voichek** [comment]
Can I close this issue?

**Comment by cedatorma** [comment]
Yes. Thank you for your help.
